.gitignore
_data/navigation.yml
_includes/category_index_pages/algo_dev_index.html
_includes/post-grid.html
_layouts/article_page.html
_layouts/category_index.html
_layouts/default.html
_posts/algorithm-development/guides/2016-05-16-guides.md
_posts/algorithm-development/guides/2016-05-16-java-guide.md
_posts/algorithm-development/guides/2016-05-16-javascript-guide.md
_posts/algorithm-development/guides/2016-05-17-python-guide.md
_posts/algorithm-development/guides/2016-05-17-ruby-guide.md
_posts/algorithm-development/guides/2016-05-17-rust-guide.md
_posts/algorithm-development/guides/2016-05-17-scala-guide.md
_posts/clients/2016-01-08-cli.md
_posts/clients/2016-05-05-node.md

Addition of algorithm docs to dev center

Algo add docs dev center

---

_pages/algorithm-development/model-guides/opencv.md

Opencv guide

---

_includes/recipe-grid.html
_layouts/default.html
_pages/tutorials/recipes.md
_pages/tutorials/recipes/404_Error_scanner.md
_pages/tutorials/recipes/car_classification.md
_pages/tutorials/recipes/censorface_videos.md
_pages/tutorials/recipes/color_extraction.md
_pages/tutorials/recipes/colorize_photos.md
_pages/tutorials/recipes/face_recognition.md
_pages/tutorials/recipes/horizon_detection.md
_pages/tutorials/recipes/language_detector.md
_pages/tutorials/recipes/named_entity_recognition.md
_pages/tutorials/recipes/scene_detection.md
_pages/tutorials/recipes/sentiment_timeseries_forecast.md
_pages/tutorials/recipes/sentiment_web_scraping.md
_pages/tutorials/recipes/sharpen_saliency.md
_pages/tutorials/recipes/site_crawler_analyzer.md
_pages/tutorials/recipes/summarize_slideshow_presentations.md
_pages/tutorials/recipes/topic_modeling_lda.md
_pages/tutorials/recipes/video_nsfw.md

DEPLOY NOTE: Requires Play deploy
Resolves [PLATFORM-1297](https://algorithmia.atlassian.net/browse/PLATFORM-1297)
Updates the styling on the recipes page. Please note that many of the styles are located in [the corresponding Play PR](https://github.com/algorithmiaio/algorithmia/pull/1540), so you'll need to point `webserver` at a locally-running version of Play if you want the styling to actually look pretty.

Revamp Recipes Page

---

_pages/clients/php.md

Like as there mistake in PHP code block

PHP code block mistake

---

_pages/pricing.md

Resolves [PLATFORM-2033](https://algorithmia.atlassian.net/browse/PLATFORM-2033)

Add note that pricing is public-marketplace-only

---

_pages/algorithm-development/comparing-algorithms.md

As per the conversation with @peckjon , we've decided to direct link example evaluator docs into the evaluations guide.

ALGO-493 Describe return vals etc for Evaluator function

---

_includes/video-responsive.html

DEPLOY NOTE: Don't merge until the [web PR](https://github.com/algorithmiaio/web/pull/811)  is deployed to prod.
Resolves [FRONTEND-495](https://algorithmia.atlassian.net/browse/FRONTEND-495)

Remove Style Tag From Video Embed

---

_config-web.yml

Resolves the dev-center side of FRONTEND-1514(https://algorithmia.atlassian.net/browse/FRONTEND-1514)

FRONTEND-1514 Add web config for CDN url override

---

Dockerfile

Resolves [FRONTEND-1659](https://algorithmia.atlassian.net/browse/FRONTEND-1659)

FRONTEND-1659 Add Dockerfile to dev-center

---

.gitlab-ci.yml

Resolves [FRONTEND-1700](https://algorithmia.atlassian.net/browse/FRONTEND-1700)
I opted to follow an approach similar to what we're doing in web as opposed to following the ticket directly. Every push will build out an image to verify the build isn't broken (using builder images to leverage the cache and keep things speedy), but only changes to `develop|master` will deploy images to Docker Hub.
You can see the CI stages [here](https://gitlab.com/algorithmia-eng/dev-center/pipelines/85886588).

Frontend 1700

---

_pages/guides/sentiment-analysis.md

Resolves [FRONTEND-1755](https://algorithmia.atlassian.net/browse/FRONTEND-1755).

Port Special Case Redirect

---

server/index.js

Resolves [FRONTEND-1939](https://algorithmia.atlassian.net/browse/FRONTEND-1939).

Ensure 404 Page is Returned to User

---

.gitlab-ci.yml
_layouts/archive.html
_layouts/article.html
_layouts/article_page.html
_layouts/article_snippets.html
_layouts/faq.html
_layouts/media.html
_layouts/synapse-default.html
_pages/platform/algorithm-profiles.md
index.html

Resolves [FRONTEND-1868](https://algorithmia.atlassian.net/browse/FRONTEND-1868)
**Things this does do:**
* Renders all pages in the main-page section of synapse layout
**Things this does not do (coming later):**
* Format content nicely within the main page section
* Include side menu links

Frontend 1868 - Render Dev Center Content in Synapse Layout

---

_includes/header.html

This is in test: https://test.algorithmia.com/developers
https://algorithmia.atlassian.net/browse/FRONTEND-1952

FRONTEND-1952 Fix brand title flash

---

_config.yml
_layouts/synapse-default.html
_pages/api.md
js/api-docs-redirect.js
server/index.js

Resolves [FRONTEND-1899](https://algorithmia.atlassian.net/browse/FRONTEND-1899)
Using `feature/FRONTEND-1875` as a feature branch for all of these subtasks

Frontend 1899 - Add API Docs Intro Page to Jekyll App

---

_pages/api/api-specification.md
css/devcenter.scss
js/api-docs-redirect.js

Resolves [FRONTEND-1901](https://algorithmia.atlassian.net/browse/FRONTEND-1901)

Frontend 1901 - Add API Specification Page

---

_layouts/synapse-default.html
e2e/pages/gettingStarted.js
e2e/tests/developers.spec.js
src/api/user.js
src/components/CodeSample.vue
src/main.js
src/utils/replaceUserCreds.js
src/utils/setupPage.js

Resolves [FRONTEND-1897](https://algorithmia.atlassian.net/browse/FRONTEND-1897).
Note: I based this off of FRONTEND-1900 so that I'd be able to test against `/developers/getting-started` as well as `/developers/api/authentication`. I set the base branch as 1900 to make the diff much easier to see.

Frontend 1897

---

_pages/api/api-versioning.md
js/api-docs-redirect.js

Resolves [FRONTEND-1903](https://algorithmia.atlassian.net/browse/FRONTEND-1903)

Frontend 1903 - Add API Versioning Page

---

_pages/api/algorithm-development.md
js/api-docs-redirect.js

Resolves [FRONTEND-1905](https://algorithmia.atlassian.net/browse/FRONTEND-1905)

Frontend 1905 - Add Algorithm Development API Docs Page

---

_pages/api/data-api-specification.md
js/api-docs-redirect.js

Resolves [FRONTEND-1902](https://algorithmia.atlassian.net/browse/FRONTEND-1902)

Frontend 1902 - Add Data Api Page to Jekyll

---

_pages/api/clients.md
js/api-docs-redirect.js

Resolves [FRONTEND-1904](https://algorithmia.atlassian.net/browse/FRONTEND-1904)

Frontend 1904 - Add Clients Page to Jekyll

---

_pages/api/need-help.md
js/api-docs-redirect.js

Resolves [FRONTEND-1907](https://algorithmia.atlassian.net/browse/FRONTEND-1907)

Frontend 1907 - Add "Need Help?" API Docs Page to Jekyll

---

_pages/api/algorithm-management-api.md
js/api-docs-redirect.js

Resolves [FRONTEND-1906](https://algorithmia.atlassian.net/browse/FRONTEND-1906)

Frontend 1906 - Add Algorithm Management API Docs Page

---

_includes/synapse-menu.html
css/devcenter.scss
jest/SideNavMenu.spec.js
jest/__snapshots__/SideNavMenu.spec.js.snap
src/components/SideNavMenu.vue
src/main.js

Resolves dev-center side of [FRONTEND-1999](https://algorithmia.atlassian.net/browse/FRONTEND-1999)
**Notes:**
* Relies on styles in https://github.com/algorithmiaio/synapse/pull/189
* You'll likely need to build the synapse dist files in order for this to look right

Frontend 1999 - Make Side Nav Toggleable

---

README.md
_layouts/synapse-default.html
config/index.js
package.json
server/customization.js
server/index.js

Resolves [FRONTEND-1871](https://algorithmia.atlassian.net/browse/FRONTEND-1871)

Frontend 1871

---

_includes/breadcrumb-section.html
_includes/breadcrumbs.html

Resolves [FRONTEND-1869](https://algorithmia.atlassian.net/browse/FRONTEND-1869)

Frontend 1869 - Dev Center Breadcrumbs

---

_includes/nav-menu.html
_layouts/synapse-default.html
_plugins/page_toc.rb
css/devcenter.scss
package-lock.json
package.json
src/main.js

Resolves dev-center side of [FRONTEND-1887](https://algorithmia.atlassian.net/browse/FRONTEND-1887)
Relies on style changes in https://github.com/algorithmiaio/synapse/pull/191
Please make sure to rebuild synapse and vue

Frontend 1887 - Highlight active subheader

---

_pages/algorithm-development.md
src/main.js

Resolves [FRONTEND-2074](https://algorithmia.atlassian.net/browse/FRONTEND-2074)

FRONTEND-2074 Use card for getting started page

---

.babelrc
jest/CodeSample.spec.js
package-lock.json
package.json

- ✅ Fix object rest spread syntax error when running in Jest
- ✅ Fix `cannot read property 'getters' of undefined error
- ✅ Add pre-push hook to run Jest tests before each push

Fix jest issue

---

src/main.js

Small fix because the vue app wasn't building for me

Remove duplicate import in main.js

---

_includes/video-responsive.html
css/devcenter.scss

Resolves [FRONTEND-2066](https://algorithmia.atlassian.net/browse/FRONTEND-2066)

Frontend 2066 - Fix Video Formatting

---

_layouts/synapse-default.html
src/enums/Cookie.js
src/main.js
src/store/user.js
test/user.spec.ts

No changes you haven't already reviewed, just realized I forgot to update my base branch before merging. This just adds the left nav changes to 1813.

1972 clone

---

_pages/algorithm-development/advanced-algorithm-development/batch-processing.md
_pages/algorithm-development/advanced-algorithm-development/list-packages.md
_pages/algorithm-development/advanced-algorithm-development/local-development.md
_pages/algorithm-development/algorithm-errors.md
_pages/algorithm-development/languages/javascript.md
_pages/algorithm-development/languages/python.md
_pages/data/dynamodb.md
_pages/data/hdfs.md
_pages/data/mssqlserver.md
_pages/data/mysql.md
_pages/data/oracle.md
_pages/data/otherfiles.md
_pages/data/postgres.md
_pages/data/snowflake.md
_pages/integrations/base64_files.md
_pages/integrations/multipartforms.md
_pages/model-deployment/tensorflow.md
_pages/model-deployment/xgboost.md
_pages/platform/algorithm-profiles.md

Resolves [FRONTEND-2068](https://algorithmia.atlassian.net/browse/FRONTEND-2068)

Frontend 2068 - Update Code Snippets to Use Highlight

---

_pages/tutorials.md

Resolves [FRONTEND-2070](https://algorithmia.atlassian.net/browse/FRONTEND-2070)

FRONTEND-2070 Tutorials Overview Formatting

---

_includes/recipe-grid.html

Resolves [FRONTEND-2071](https://algorithmia.atlassian.net/browse/FRONTEND-2071)
**Note:** The odd-looking hexicon at the top will be going away in another ticket

Frontend 2071 - Update Recipes Page Layout
